export type Player = {
  PlayerName: string,
  Pos: string,
  Age: number,
  Tm: string,
  G: number,
  GS: number,
  MP: number,
  FG: number,
  FGA: number,
  FGcent: number,
  ThreeP: number,
  ThreePA: number,
  ThreePcent: number,
  TwoP: number,
  TwoPA: number,
  TwoPcent: number,
  //eFGcent: number,
  FT: number,
  FTA: number,
  FTcent: number,
  ORB: number,
  DRB: number
  TRB: number
  AST: number
  STL: number
  BLK: number
  TOV: number
  PF: number
  PTS: number
  PlayerAdditional: string,
  ContractPrice: number
}