export type SaveTeamFormat = {
  team_id: string,
  team_name: string,
  year: number,
  budget: number,
  player1: string | null,
  player2: string | null,
  player3: string | null,
  player4: string | null,
  player5: string | null,
  player6: string | null,
  player7: string | null,
  player8: string | null,
  player9: string | null,
  player10: string | null,
  player11: string | null,
  player12: string | null,
  player13: string | null,
  player14: string | null,
  player15: string | null,
  owner: string,
  losses: number,
  wins: number,
  winloss: number,
}